config/routes.rb
Rails.application.routes.draw do
  get 'ordinateurs/new'
  get 'emprunts/new'
  get 'sessions/destroy'
  get 'sessions/create'

  root 'main#index'
  get 'registrations/new'
  get 'main/new'
  get 'main/create'
  
  get 'login' , to: 'sessions#new'   # login_path 
  post "login" , to: "sessions#create" 
  get "logout", to: "sessions#destroy"
  get 'signup' , to: 'registrations#new'
  post "signup" , to: "registrations#create"

  resources :users do 
    collection do
      post 'search_by_id'
    end
  end
  resources :documents do 
    collection do
      #post 'index' , to: "documents#search_by_id"
      post 'search_by_id'
    end
  end
  resources :authors do
    collection do
      post 'search_by_id'
    end
  end
  resources :emprunts do 
    collection do
      post 'search_by_id'
    end
  end
  resources :ordinateurs do 
    collection do
      post 'search_by_id'
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :admin , only: [:new, :create, :destroy]
  def new
    @author = Author.new
  end

  def create 
    author = Author.new(author_params)
    if author.save
      flash[:success] = "Auteur créé avec succès"
      redirect_to author
    else
      flash.now[:alert] = "Erreur lors de la création de l'auteur"
      render :new
    end
  end

  def index
    @authors = Author.paginate(page: params[:page], per_page: 5)
  end

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    Author.find(params[:id]).destroy
    flash[:sucess] = "Auteur supprimé"
    redirect_to root_url
  end

  def search_by_id
    @author = Author.find_by(id: params[:id])
    if @author
      render :show
    else
      flash.now[:alert] = "Auteur introuvable"
      render :search
    end 
  end
  
  def author_params
    params.require(:author).permit(:nom, :prenom, :email)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/athenticate.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Vertically centered hero sign-up form</h1>
            <p class="col-lg-10 fs-4">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
            <form class="p-4 p-md-5 border rounded-3 bg-body-tertiary", method="post">
                <%= form_for(:author, url: author_login_path) do |f| %>
                    <div class="form-floating mb-3">
                        <%= f.email_field :email, class: "form-control", id: "floatingInput", placeholder: "your email" %>
                        <%= f.label :email, "Email address", class: "form-label", for: "floatingInput" %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= f.password_field :password, class: "form-control", id: "floatingPassword", placeholder: "Password" %>
                        <%= f.label :password, "Password", class: "form-label", for: "floatingPassword" %>
                    </div>
                    <%= f.submit "login", class: "w-100 btn btn-lg btn-primary" %>
                    <hr class="my-4">
                    <small class="text-body-secondary">By clicking Sign up, you agree to the terms of use.</small>
                <% end %>
            </form>
        </div>
    </div>
</div>

app/views/authors/create.html.erb
<h1> Hellooooo author </h1>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<div class="container">
  <h1>Tous les auteurs</h1>
  <ul class="auteurs">
    <% if logged_in? %>
      <% @authors.each do |author| %>
        <li>
        <button class="btn btn-success rounded-pill px-3" type="button">
              <%= link_to author.nom, author ,class: "text-decoration-none text-white"%>
        </button>
          <% if @current_user.admin? %>
            <div class="my-3 p-3 bg-body rounded shadow-sm">
              <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
                <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                  <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark"></strong>
                    <button class="btn btn-danger rounded-pill px-3 " type="button"> 
                    <%= link_to "delete", author,class: "text-decoration-none text-white", method: :delete, data: { confirm: "confirmer" } %>
                    </button>
                  </div>
                </div>
              </div>
          <% end %>
        </li>  
      <% end %>
    <% end %>
  </ul>

  <%= will_paginate @authors, class: "pagination justify-content-center" %>

  <%= link_to "New Author", new_author_path, class: "btn btn-primary" %>

  <%= form_with model: @author, url: search_by_id_authors_path, class: "mt-3" do |form| %>
    <div class="input-group">
      <%= form.number_field :id, class: "form-control", placeholder: "Search user by ID" %>
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Your place to thrive as an inspiring Author</h1>
            <p class="col-lg-10 fs-4">join our community and share your best with us!!!</p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
            <%= form_with(model: @author, url: authors_path, class: "p-4 p-md-5 border rounded-3 bg-body-tertiary") do |form| %>
                <% if @author.errors.any? %>
                    <div class="alert alert-danger">
                        <% @author.errors.full_messages.each do |messages| %>
                            <p><%= messages %></p>
                        <% end %>
                    </div>
                <% end %>
                <div class="form-floating mb-3">
                    <%= form.text_field :nom, class: "form-control", id: "floatingNom", placeholder: "Your name" %>
                    <%= form.label :nom, "Nom", class: "form-label", for: "floatingNom" %>
                </div>
                <div class="form-floating mb-3">
                    <%= form.text_field :prenom, class: "form-control", id: "floatingPrenom", placeholder: "Your prenom" %>
                    <%= form.label :prenom, "Prenom", class: "form-label", for: "floatingPrenom" %>
                </div>
                <div class="form-floating mb-3">
                    <%= form.email_field :email, class: "form-control", id: "floatingInput", placeholder: "your email" %>
                    <%= form.label :email, "Email address", class: "form-label", for: "floatingInput" %>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-floating mb-3">
                    <%= form.password_field :password, class: "form-control", id: "floatingPassword", placeholder: "Password" %>
                    <%= form.label :password, "Password", class: "form-label", for: "floatingPassword" %>
                </div>
                <div class="form-floating mb-3">
                    <%= form.password_field :password_confirmation, class: "form-control", id: "floatingPasswordConfirmation", placeholder: "Password Confirmation" %>
                    <%= form.label :password_confirmation, "Password Confirmation", class: "form-label", for: "floatingPasswordConfirmation" %>
                </div>
                <%= form.submit "Sign Up", class: "w-100 btn btn-lg btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/authors/show.html.erb
<%= @author.id %>
<%= @author.nom %>
<%= @author.prenom %>
<%= @author.email %>