config/routes.rb
Rails.application.routes.draw do
  get 'ordinateurs/new'
  get 'emprunts/new'
  get 'sessions/destroy'
  get 'sessions/create'

  root 'main#index'
  get 'registrations/new'
  get 'main/new'
  get 'main/create'
  
  get 'login' , to: 'sessions#new'   # login_path 
  post "login" , to: "sessions#create" 
  get "logout", to: "sessions#destroy"
  get 'signup' , to: 'registrations#new'
  post "signup" , to: "registrations#create"

  resources :users do 
    collection do
      post 'search_by_id'
    end
  end
  resources :documents do 
    collection do
      #post 'index' , to: "documents#search_by_id"
      post 'search_by_id'
    end
  end
  resources :authors do
    collection do
      post 'search_by_id'
    end
  end
  resources :emprunts do 
    collection do
      post 'search_by_id'
    end
  end
  resources :ordinateurs do 
    collection do
      post 'search_by_id'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
 # Un utilisateur peut avoir plusieurs emprunts
    has_many :emprunts
    
    validates :nom , presence: true , length: {maximum: 50}
    validates :prenom , presence: true , length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email , presence: true , length: {maximum: 255} , 
        format: {with: VALID_EMAIL_REGEX , message: "Format d'email invalide"} ,
        uniqueness: {case_sensitive: false}
    
    has_secure_password  # Ajout de la méthode has_secure_password pour le hachage du mot de passe
    validates :password , presence: true , length: {minimum: 6} 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, :only => [:index, :edit, :update, :destroy]
  before_action :good_user,  only: [:edit, :update]
  before_action :user_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5) # Affichage de tous les utilisateurs
  end

  def show
    @user = User.find(params[:id]) # Affichage d'un utilisateur
  end

  def edit
    @user = User.find(params[:id]) # Edition d'un utilisateur
  end
  def destroy 
    User.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprimé"
    redirect_to users_path
  end

  def user_admin
    @user = User.find(params[:id]) # Affichage d'un utilisateur
    if not @current_user.admin? || @user == @current_user
      redirect_to root_path
    end
  end

  def authenticate 
    unless logged_in?
      flash[:alert] = "Connectez-vous pour accéder à cette page"
      redirect_to login_path
    end
  end

  def search_by_id
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      flash.now[:alert] = "Utilisateur introuvable"
      render :search
    end
  end


  def good_user
    @user = User.find(params[:id]) # Affichage d'un utilisateur
    redirect_to root_path unless @user == @current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/good_user.html.erb
<h1>Users#good_user</h1>
<p>Find me in app/views/users/good_user.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <h1>Tous les utilisateurs</h1>
  <ul class="ordinateur">
    <% if logged_in? %>
      <% @users.each do |utilisateur| %>
        <li>
        <button class="btn btn-success rounded-pill px-3" type="button">
              <%= link_to utilisateur.nom, utilisateur ,class: "text-decoration-none text-white"%>
        </button>
          <% if @current_user.admin? %>
            <div class="my-3 p-3 bg-body rounded shadow-sm">
              <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
                <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                  <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark"></strong>
                    <button class="btn btn-danger rounded-pill px-3 " type="button"> 
                    <%= link_to "delete", utilisateur,class: "text-decoration-none text-white", method: :delete, data: { confirm: "confirmer" } %>
                    </button>
                  </div>
                </div>
              </div>
          <% end %>
        </li>  
      <% end %>
    <% end %>
  </ul>

  <%= will_paginate @users, class: "pagination justify-content-center" %>

  <%= link_to "Nouveau utilisateur", registrations_new_path, class: "btn btn-primary" %>

  <%= form_with model: @user, url: search_by_id_users_path, class: "mt-3" do |form| %>
    <div class="input-group">
      <%= form.number_field :id, class: "form-control", placeholder: "Search user by ID" %>
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="d-flex justify-content-center">
  <div class="col">
    <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('<%= asset_path('Library Animation Background.jpeg') %>'); background-size: center;">
      <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold"><%= @user.nom %> <%= @user.prenom %></h3>
        <ul class="d-flex list-unstyled mt-auto">
          <li class="me-auto">
            <%= image_tag("salah-eddine_zaame.jpg", alt: "Bootstrap", class: "rounded-circle border border-white", width: 32, height: 32) %>
          </li>
          <li class="d-flex align-items-center me-3">
            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
          </li>
          <li class="d-flex align-items-center">
            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/user_admin.html.erb
<h1>Users#user_admin</h1>
<p>Find me in app/views/users/user_admin.html.erb</p>