config/routes.rb
Rails.application.routes.draw do
  get 'ordinateurs/new'
  get 'emprunts/new'
  get 'sessions/destroy'
  get 'sessions/create'

  root 'main#index'
  get 'registrations/new'
  get 'main/new'
  get 'main/create'
  
  get 'login' , to: 'sessions#new'   # login_path 
  post "login" , to: "sessions#create" 
  get "logout", to: "sessions#destroy"
  get 'signup' , to: 'registrations#new'
  post "signup" , to: "registrations#create"

  resources :users do 
    collection do
      post 'search_by_id'
    end
  end
  resources :documents do 
    collection do
      #post 'index' , to: "documents#search_by_id"
      post 'search_by_id'
    end
  end
  resources :authors do
    collection do
      post 'search_by_id'
    end
  end
  resources :emprunts do 
    collection do
      post 'search_by_id'
    end
  end
  resources :ordinateurs do 
    collection do
      post 'search_by_id'
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
    #has_many :emprunts # Un document peut être emprunté plusieurs fois
    validates :titre , presence: true # Un document doit avoir un titre
    validates :document_type , presence: true # Un document doit avoir un type
    validates :author, presence: true # Un document doit avoir un auteur
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :admin , only: [:new, :create, :destroy]

  def new
    @document = Document.new
  end
  def index 
    @documents = Document.paginate(page: params[:page], per_page: 5)
    @document = Document.new
  end



  def create
    @document = Document.new(document_params)
    if @document.save
      flash[:success] = "Document créé avec succès"
      redirect_to @document
    else
      flash.now[:alert] = "Erreur lors de la création du document"
      render :new
    end
  end

  def show
    @document = Document.find(params[:id])
  end

  def destroy
    Document.find(params[:id]).destroy
    flash[:success] = "Document supprimé"
    redirect_to documents_path
  end

  def search_by_id
    @document = Document.find_by(id: params[:document][:id])
    if @document
      render :show
    else
      flash.now[:alert] = "Document introuvable"
      render :search
    end
  end
  private

  def document_params
    params.require(:document).permit(:titre, :document_type, :author)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/delete.html.erb
<h1>Documents#delete</h1>
<p>Find me in app/views/documents/delete.html.erb</p>

app/views/documents/index.html.erb
<div class="container">
  <h1>Tous les documents</h1>
  <ul class="document">
    <% if logged_in? %>
      <% @documents.each do |document| %>
        <li>
        <button class="btn btn-success rounded-pill px-3" type="button">
              <%=  link_to document.titre, document ,class: "text-decoration-none text-white"%>
        </button>
          <% if @current_user.admin? %>
            <div class="my-3 p-3 bg-body rounded shadow-sm">
              <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
                <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                  <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark"></strong>
                    <button class="btn btn-danger rounded-pill px-3 " type="button"> 
                    <%= link_to "delete", document,class: "text-decoration-none text-white", method: :delete, data: { confirm: "confirmer" } %>
                    </button>
                  </div>
                </div>
              </div>
          <% end %>
        </li>  
      <% end %>
    <% end %>
  </ul>

  <%= will_paginate @documents, class: "pagination justify-content-center" %>

  <%= link_to "Nouveau Document", new_document_path, class: "btn btn-primary" %>

  <%= form_with model: @document, url: search_by_id_documents_path, class: "mt-3" do |form| %>
    <div class="input-group">
      <%= form.number_field :id, class: "form-control", placeholder: "Search user by ID" %>
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  <% end %>
</div>

app/views/documents/new.html.erb
<h1 class="text-center">Nouveau Document</h1>

<div class="d-flex justify-content-center">
  <main class="form-signin w-50">
    <% if logged_in? && @current_user.admin? %>
      <%= form_with(model: @document, url: documents_path) do |form| %>
        <% if @document.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

            <ul>
              <% @document.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-floating">
          <%= form.label :titre %>
          <%= form.text_field :titre, class: "form-control", id: "floatingInput", placeholder: "Titre" %>
        </div>

        <div class="form-floating">
          <%= form.label :document_type %>
          <%= form.text_field :document_type, class: "form-control", id: "floatingPassword", placeholder: "Document Type" %>
        </div>

        <div class="form-floating">
          <%= form.label :author %>
          <%= form.text_field :author, class: "form-control", placeholder: "Author" %>
        </div>

        <div class="actions">
          <%= form.submit "Créer Document", class: "w-100 btn btn-lg btn-primary" %>
        </div>
      <% end %>
    <% else %>
      <p>Vous n'avez pas les droits nécessaires pour ajouter un document.</p>
    <% end %>
  </main>
</div>
<button class="btn btn-warning rounded-pill px-3" type="button">
  <%= link_to "Retour", documents_path , class: "text-decoration-none text-white" %>
</button>

app/views/documents/show.html.erb
<h1>Détails du Document</h1>

<p><strong>Titre:</strong> <%= @document.titre %></p>
<p><strong>Type de Document:</strong> <%= @document.document_type %></p>
<p><strong>Auteur:</strong> <%= @document.author %></p>

<%= link_to "Retour", documents_path %>