config/routes.rb
Rails.application.routes.draw do
  get 'ordinateurs/new'
  get 'emprunts/new'
  get 'sessions/destroy'
  get 'sessions/create'

  root 'main#index'
  get 'registrations/new'
  get 'main/new'
  get 'main/create'
  
  get 'login' , to: 'sessions#new'   # login_path 
  post "login" , to: "sessions#create" 
  get "logout", to: "sessions#destroy"
  get 'signup' , to: 'registrations#new'
  post "signup" , to: "registrations#create"

  resources :users do 
    collection do
      post 'search_by_id'
    end
  end
  resources :documents do 
    collection do
      #post 'index' , to: "documents#search_by_id"
      post 'search_by_id'
    end
  end
  resources :authors do
    collection do
      post 'search_by_id'
    end
  end
  resources :emprunts do 
    collection do
      post 'search_by_id'
    end
  end
  resources :ordinateurs do 
    collection do
      post 'search_by_id'
    end
  end
end

app/models/ordinateur.rb
class Ordinateur < ApplicationRecord
end

app/controllers/ordinateurs_controller.rb
class OrdinateursController < ApplicationController
  def new
    @ordinateur = Ordinateur.new
  end

  def create
    ordinateur = Ordinateur.new(ordinateur_params)
    if ordinateur.save
      flash[:success] = "Ordinateur créé avec succès"
      redirect_to ordinateur
    else
      flash.now[:alert] = "Erreur lors de la création de l'ordinateur"
      render :new
    end
  end

  def index
    @ordinateurs = Ordinateur.paginate(page: params[:page], per_page: 5)
  end

  def show
    @ordinateur = Ordinateur.find(params[:id])
  end

  def destroy
    Ordinateur.find(params[:id]).destroy
    flash[:sucess] = "Ordinateur supprimé"
    redirect_to root_url
  end

  def ordinateur_params
    params.require(:ordinateur).permit(:marque, :modele)
  end

  def search_by_id
    @ordinateur = Ordinateur.find_by(id: params[:id])
    if @ordinateur
      render :show
    else
      flash.now[:alert] = "Ordinateur introuvable"
      render :search
    end
  end

  
end

app/helpers/ordinateurs_helper.rb
module OrdinateursHelper
end

app/views/ordinateurs/index.html.erb
<div class="container">
  <h1>Tous les ordinateurs</h1>
  <ul class="ordinateur">
    <% if logged_in? %>
      <% @ordinateurs.each do |ordinateur| %>
        <li>
        <button class="btn btn-success rounded-pill px-3" type="button">
              <%= link_to ordinateur.marque, ordinateur ,class: "text-decoration-none text-white"%>
        </button>
          <% if @current_user.admin? %>
            <div class="my-3 p-3 bg-body rounded shadow-sm">
              <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
                <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                  <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark"></strong>
                    <button class="btn btn-danger rounded-pill px-3" type="button"> 
                    <%= link_to "delete", ordinateur, method: :delete, data: { confirm: "confirmer" } %>
                    </button>
                  </div>
                </div>
              </div>
          <% end %>
        </li>  
      <% end %>
    <% end %>
  </ul>

  <%= will_paginate @ordinateur, class: "pagination justify-content-center" %>

  <%= link_to "Nouveau ordinateur", new_ordinateur_path, class: "btn btn-primary" %>

  <%= form_with model: @ordinateur, url: search_by_id_ordinateurs_path, class: "mt-3" do |form| %>
    <div class="input-group">
      <%= form.number_field :id, class: "form-control", placeholder: "Search ordinateur by ID" %>
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  <% end %>
</div>

app/views/ordinateurs/new.html.erb
<h1 class="text-center">Nouveau Ordinateur</h1>

<div class="d-flex justify-content-center">
  <main class="form-signin w-50">
    <% if logged_in? && @current_user.admin? %>
      <%= form_with(model: @ordinateur, url: ordinateurs_path) do |form| %>
        <% if @ordinateur.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@ordinateur.errors.count, "error") %> prohibited this ordinateur from being saved:</h2>

            <ul>
              <% @ordinateur.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-floating">
          <%= form.label :marque %>
          <%= form.text_field :marque, class: "form-control", placeholder: "Marque" %>
        </div>

        <div class="form-floating">
          <%= form.label :modele %>
          <%= form.text_field :modele, class: "form-control", placeholder: "Modele" %>
        </div>

        <div class="actions">
          <%= form.submit "Créer ordinateur", class: "w-100 btn btn-lg btn-primary" %>
        </div>

      <% end %>
    <% else %>
      <p>Vous n'avez pas les droits nécessaires pour ajouter un ordinateur.</p>
    <% end %>
  </main>
</div>
<button class="btn btn-warning rounded-pill px-3" type="button">
<%= link_to "Retour", ordinateurs_path , class: "text-decoration-none text-white"%>
</button>

app/views/ordinateurs/show.html.erb
<h1>Détails du ordinateur</h1>

<p><strong>Titre:</strong> <%= @ordinateur.marque %></p>
<p><strong>Type de ordinateur:</strong> <%= @ordinateur.modele %></p>

<%= link_to "Retour", ordinateurs_path %>